name: 'Trasform GitHub lab to Github skills format'
description: 'Take a config.yml, parse it into a README.md'
inputs:
  config-file:  # config.yml
    description: 'config.yml path'
    required: true
    default: 'config.yml'
  coursedetailsfile: # course-details.md
    description: 'course-details.md path'
    required: true
    default: 'course-details.md'
outputs:
  readme:
    description: 'The genereated README.md from config.yml + course-details.md'
runs:
  using: 'node16'
  main: 'dist/index.js'
