name: 'Trasform GitHub lab to Github skills format'
description: 'Take a config.yml, parse it into a README.md'
inputs:
  config-file:  # config.yml
    description: 'config.yml path'
    required: true
    default: 'config.yml'
# outputs:
#   time: # output will be available to future steps
#     description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
